export const FETCH_QUIZZES_START = 'FETCH_QUIZZES_START'
export const FETCH_QUIZZES_SUCCESS = 'FETCH_QUIZZES_SUCCESS'
export const FETCH_QUIZZES_ERROR = 'FETCH_QUIZZES_ERROR'

export const SET_ACTIVE_TYPE = 'SET_ACTIVE_TYPE'
export const SET_ACTIVE_CATEGORY = 'SET_ACTIVE_CATEGORY'

export const SET_FILTER = 'SET_FILTER'
export const SET_SORT = 'SET_SORT'

//cart
export const GET_CART_ITEM = 'GET_CART_ITEM'
export const SET_MESSAGE = 'SET_MESSAGE'
export const GET_COUNT = 'SET_COUNT'
export const GET_ALL_PRICE = 'GET_ALL_PRICE'

export const CLEAR_CART = 'CLEAR_CART'
export const EDIT_CART = 'EDIT_CART'

//pagination
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE'
export const SET_PAGE_NUMBERS = 'SET_PAGE_NUMBERS'